import os
import platform
import shutil
import subprocess
import tempfile
import textwrap
import time
from pathlib import Path

arch = platform.machine()
arch_setting = "armv8" if arch in ["arm64", "aarch64"] else arch
default_profiles = {
    "Windows": textwrap.dedent("""\
        [settings]
        os=Windows
        arch=x86_64
        """),
    "Linux": textwrap.dedent(f"""\
        [settings]
        os=Linux
        arch={arch_setting}
       
        """),
    "Darwin": textwrap.dedent(f"""\
        [settings]
        os=Macos
        arch={arch_setting}
        """)
}


def load(path, encoding="utf-8"):
    with open(path, "r", encoding=encoding, newline="") as handle:
        tmp = handle.read()
        return tmp


def save(path, content, append=False, encoding="utf-8"):
    dir_path = os.path.dirname(path)
    if dir_path:
        os.makedirs(dir_path, exist_ok=True)
    with open(path, "a" if append else "w", encoding=encoding, newline="") as handle:
        handle.write(content)


def temp_folder(path_with_spaces=True, create_dir=True):
    t = tempfile.mkdtemp(suffix='conans')
    # Make sure that the temp folder is correctly cased, as tempfile return lowercase for Win
    # t = get_cased_path(t)
    # necessary for Mac OSX, where the temp folders in /var/ are symlinks to /private/var/
    t = os.path.realpath(t)
    # FreeBSD and Solaris do not use GNU Make as a the default 'make' program which has trouble
    # with spaces in paths generated by CMake
    path = "pathnospace" if not path_with_spaces else "path space"
    nt = os.path.join(t, path)
    if create_dir:
        os.makedirs(nt)
    return nt


class TestClient:
    """ Test wrap of the conans application to launch tests in the same way as
    in command line
    """
    # Preventing Pytest collects any tests from here
    __test__ = False

    def __init__(self, cache_folder=None, current_folder=None, path_with_spaces=True):
        """
        current_folder: Current execution folder
        servers: dict of {remote_name: TestServer}
        logins is a list of (user, password) for auto input in order
        if required==> [("lasote", "mypass"), ("other", "otherpass")]
        """

        # Adding the .conan2, so we know clearly while debugging this is a cache folder
        self.cache_folder = cache_folder or os.path.join(temp_folder(path_with_spaces), ".conan2")
        self.current_folder = current_folder or temp_folder(path_with_spaces)

        # Once the client is ready, modify the configuration
        os.makedirs(self.current_folder, exist_ok=True)
        self.out = ""

        # create default profile
        text = default_profiles[platform.system()]
        save(os.path.join(self.cache_folder, "profiles", "default"), text)

    def load(self, filename):
        return load(os.path.join(self.current_folder, filename))

    def save(self, files, clean_first=False):
        """ helper metod, will store files in the current folder
        param files: dict{filename: filecontents}
        """
        if clean_first:
            shutil.rmtree(self.current_folder, ignore_errors=True)
        for f, content in files.items():
            save(os.path.join(self.current_folder, f), content)

    def run(self, command, assert_error=False):
        ret = subprocess.run(command, cwd=self.current_folder, text=True, capture_output=True, shell=True)
        self.out = ret.stderr + ret.stdout
        if ret.returncode != 0 and not assert_error:
            raise Exception(f"Error: {command}\n{self.out}")
        if ret.returncode == 0 and assert_error:
            raise Exception(f"Failure expected: {command}\n{self.out}")

    @property
    def provider(self):
        src_dir = Path(__file__).parent.parent
        return src_dir / "conan_provider.cmake"


def test():
    c = TestClient()
    c.run("conan new header_lib -d name=hello -d version=1.0")
    c.run("conan create -tf=")

    cmake = textwrap.dedent("""\
        set(CMAKE_C_COMPILER_WORKS 1)
        cmake_minimum_required(VERSION 3.24)
        project(MyApp C)
        
        find_package(hello REQUIRED)
        """)
    conanfile = textwrap.dedent("""\
        [requires]
        hello/[*]
        [generators]
        CMakeConfigDeps
        """)
    c.save({"CMakeLists.txt": cmake,
            "conanfile.txt": conanfile}, clean_first=True)

    c.run(f"cmake . -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES={c.provider}")
    assert "Conan: Target declared 'hello::hello'" in c.out
